# Theo dõi lịch sử của tensor torch


In [1]:
import torch

Cách lưu đồ thị tính toán

In [2]:
#C1: set requires_grad = True
x = torch.rand(5,3 , requires_grad=True)
print (x)
y = x + 3
print (y)

tensor([[0.7717, 0.7736, 0.9060],
        [0.5469, 0.6072, 0.1105],
        [0.8270, 0.3252, 0.4099],
        [0.4109, 0.3297, 0.9835],
        [0.9155, 0.3710, 0.3406]], requires_grad=True)
tensor([[3.7717, 3.7736, 3.9060],
        [3.5469, 3.6072, 3.1105],
        [3.8270, 3.3252, 3.4099],
        [3.4109, 3.3297, 3.9835],
        [3.9155, 3.3710, 3.3406]], grad_fn=<AddBackward0>)


In [3]:
print(y.grad_fn)

In [4]:
z = y*y
k = z.mean()
print(z)
print(k)

tensor([[14.2260, 14.2401, 15.2566],
        [12.5808, 13.0120,  9.6755],
        [14.6460, 11.0571, 11.6273],
        [11.6340, 11.0872, 15.8686],
        [15.3311, 11.3637, 11.1599]], grad_fn=<MulBackward0>)
tensor(12.8511, grad_fn=<MeanBackward0>)


In [5]:
#C2 : Sử dụng inplace function.
a = torch.rand(5,3)
print(a)
b = a + 2
print(b)
a.requires_grad_(True)
print(a)
c = a+2
print(c)

tensor([[0.9721, 0.1717, 0.8092],
        [0.3696, 0.1917, 0.0066],
        [0.8254, 0.4133, 0.1532],
        [0.8074, 0.1137, 0.4472],
        [0.7376, 0.9934, 0.2971]])
tensor([[2.9721, 2.1717, 2.8092],
        [2.3696, 2.1917, 2.0066],
        [2.8254, 2.4133, 2.1532],
        [2.8074, 2.1137, 2.4472],
        [2.7376, 2.9934, 2.2971]])
tensor([[0.9721, 0.1717, 0.8092],
        [0.3696, 0.1917, 0.0066],
        [0.8254, 0.4133, 0.1532],
        [0.8074, 0.1137, 0.4472],
        [0.7376, 0.9934, 0.2971]], requires_grad=True)
tensor([[2.9721, 2.1717, 2.8092],
        [2.3696, 2.1917, 2.0066],
        [2.8254, 2.4133, 2.1532],
        [2.8074, 2.1137, 2.4472],
        [2.7376, 2.9934, 2.2971]], grad_fn=<AddBackward0>)


# Gradients

In [6]:
x = torch.tensor(2. , requires_grad = True)
y = x**3
print(y)

tensor(8., grad_fn=<PowBackward0>)


In [7]:
print(x.grad) # Kết quả trả về None do chưa có  backward
y.backward() # đạo hàm
            # Sau khi đạo hàm x^3 sẽ bằng 3x^2 với x = 2 => 3x^2 = 12
print(x.grad)

None
tensor(12.)
