# Autograd
Chức năng của autograd: Tự động tính toán đạo hàm trên toàn bộ các toán tử của tensors. Nó là một framework được định nghĩa trong quá trình chạy, có nghĩa rằng quá trình lan truyền ngược được xác định khi mà code được chạy, và do đó mỗi vòng lặp có thể có kết quả thay đổi tham số theo lan truyền ngược khác nhau.

ví dụ : 
Cho đồ thị tính toán như hình. Đầu vào [x,y,z] = [5,3,7]. Tất cả các trọng số w đều được khởi tạo là 0.5. Tính kết quả (biến result) khi ta cho [x,y,z] qua mạng (forward) và gradient của mỗi trọng số w (backward).
<img src="https://images.viblo.asia/b2015661-42b6-4992-9ab9-3a9036ddc206.png">

In [10]:
import torch
from torch.autograd import Variable

In [16]:
x = Variable(torch.FloatTensor([5]), requires_grad=True)
y = Variable(torch.FloatTensor([3]), requires_grad=True)
z = Variable(torch.FloatTensor([7]), requires_grad=True)
w1 = Variable(torch.FloatTensor([0.5]), requires_grad=True)
w2 = Variable(torch.FloatTensor([0.5]), requires_grad=True)
w3 = Variable(torch.FloatTensor([0.5]), requires_grad=True)
w4 = Variable(torch.FloatTensor([0.5]), requires_grad=True)
w5 = Variable(torch.FloatTensor([0.5]), requires_grad=True)


In [17]:
o1 = x*w1 * y*w2
o2 = o1*w4 + z*w3
result = o2*w5

In [21]:
# Forward
print('result', result.item())

result 2.6875


giải thích Forward :

result = (( x * w1  *  y * w2 )* w4 + y * w3 )* w5

In [19]:
#Backward
result.backward()

In [20]:
print(w1.grad)
print(w2.grad)
print(w3.grad)
print(w4.grad)
print(w5.grad)

tensor([1.8750])
tensor([1.8750])
tensor([3.5000])
tensor([1.8750])
tensor([5.3750])


Công thức đạo hàm hợp : f'(u(x)) = f'(u) * u'(x)

Giải thích backward :

w5 = f'(w5) = ( o2 * w5 )' = o2 = (( x * w1 * y * w2 )* w4 + y * w3 )

w4 = f'(o2) * o2'(w4) = w5 * o1 = 

w3 = f'(o2) * o2'(w3) = w5 * z  =

w2 = g'(o1) * o1'(w2)

w1 = g'(o1) * o1'(w1)