# Tensor trong Torch

In [1]:
import torch
torch.__version__

'1.5.1'

In [2]:
# tạo ma trận trống
x = torch.empty(4, 3)
x

tensor([[3.9608e+28, 3.0950e-41, 3.9608e+28],
        [3.0950e-41, 1.5975e-43, 0.0000e+00],
        [1.6675e-43, 0.0000e+00, 4.0379e+28],
        [3.0950e-41, 4.0379e+28, 3.0950e-41]])

In [3]:
# Khởi tạo một ma trận ngẫu nhiên
x = torch.rand(4, 3)
print(x)

tensor([[0.9059, 0.4481, 0.9663],
        [0.4279, 0.7903, 0.5990],
        [0.4903, 0.1065, 0.5230],
        [0.3170, 0.1645, 0.9951]])


In [4]:
# check size
x.size()

torch.Size([4, 3])

In [5]:
# phép cộng
a = torch.rand(4, 3)
print(a)
b = torch.rand(4, 3)
print(b)
c = a+b
print(c)
print(a.add(b))

tensor([[0.0547, 0.9222, 0.3149],
        [0.2124, 0.9690, 0.7654],
        [0.1835, 0.6610, 0.1479],
        [0.7806, 0.9881, 0.7181]])
tensor([[0.7731, 0.8900, 0.2032],
        [0.6890, 0.6259, 0.2708],
        [0.0431, 0.2189, 0.4063],
        [0.0063, 0.0673, 0.9037]])
tensor([[0.8278, 1.8122, 0.5181],
        [0.9014, 1.5949, 1.0361],
        [0.2267, 0.8800, 0.5542],
        [0.7869, 1.0554, 1.6219]])
tensor([[0.8278, 1.8122, 0.5181],
        [0.9014, 1.5949, 1.0361],
        [0.2267, 0.8800, 0.5542],
        [0.7869, 1.0554, 1.6219]])


In [6]:
# cộng và thay thế ngay trên y ( inplace)
print(b)
print(b.add_(a))
print(b)

tensor([[0.7731, 0.8900, 0.2032],
        [0.6890, 0.6259, 0.2708],
        [0.0431, 0.2189, 0.4063],
        [0.0063, 0.0673, 0.9037]])
tensor([[0.8278, 1.8122, 0.5181],
        [0.9014, 1.5949, 1.0361],
        [0.2267, 0.8800, 0.5542],
        [0.7869, 1.0554, 1.6219]])
tensor([[0.8278, 1.8122, 0.5181],
        [0.9014, 1.5949, 1.0361],
        [0.2267, 0.8800, 0.5542],
        [0.7869, 1.0554, 1.6219]])


In [7]:
# chuyển torch sang numpy
d = a.numpy()
print(type(a))
print(type(d))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


In [8]:
# chuyển numpy sang torch
import numpy as np
e = np.random.rand(4,3)
f = torch.from_numpy(e)
print(type(e))
print(type(f))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [9]:
# tính toán trên cuda
if torch.cuda.is_available():
    device = torch.device("cuda") # Khởi tạo một cuda device object
    y = torch.ones_like(x, device = device) # Trực tiếp khởi tạo một tensor trên GPU
    x = x.to(device) # Truyền giá trị tensor vào thiết bị. Có thể truyền vào tên thiết bị: .to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double)) # Trong hàm .to() ta có thể thay định dạng dữ liệu.

tensor([[1.9059, 1.4481, 1.9663],
        [1.4279, 1.7903, 1.5990],
        [1.4903, 1.1065, 1.5230],
        [1.3170, 1.1645, 1.9951]], device='cuda:0')
tensor([[1.9059, 1.4481, 1.9663],
        [1.4279, 1.7903, 1.5990],
        [1.4903, 1.1065, 1.5230],
        [1.3170, 1.1645, 1.9951]], dtype=torch.float64)
